# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    filter_sets:
      thumbTableau:
        quality: 75
        filters:
          thumbnail:
            size:   [45, 45]
            mode:   outbound

      thumb:
        quality: 75
        filters:
          thumbnail:
                size:   [210, 100]
                mode:   inset
      medium :
        quality: 75
        filters:
          thumbnail:
                size:   [300, 300]
                mode:   inset
    # valid drivers options include "gd" or "gmagick" or "imagick"
  #driver: "gd"
